import { svgToDataUrl } from '../utils/svgDataUrl';

import appLogoRaw from './app-logo.svg?raw';
import addRaw from './icons/add.svg?raw';
import arrowDownRaw from './icons/arrow-down.svg?raw';
import arrowUpRaw from './icons/arrow-up.svg?raw';
import exportRaw from './icons/export.svg?raw';
import glossaryRaw from './icons/glossary.svg?raw';
import newProjectRaw from './icons/new-project.svg?raw';
import openProjectRaw from './icons/open-project.svg?raw';
import pauseRaw from './icons/pause.svg?raw';
import playRaw from './icons/play.svg?raw';
import saveRaw from './icons/save.svg?raw';
import searchRaw from './icons/search.svg?raw';
import sendRaw from './icons/send.svg?raw';
import stopRaw from './icons/stop.svg?raw';
import volumeMuteRaw from './icons/volume-mute.svg?raw';
import volumeRaw from './icons/volume.svg?raw';
import wizardRaw from './icons/wizard.svg?raw';
import zoomInRaw from './icons/zoom-in.svg?raw';
import zoomOutRaw from './icons/zoom-out.svg?raw';

export const appLogo = svgToDataUrl(appLogoRaw);
export const iconAdd = svgToDataUrl(addRaw);
export const iconArrowDown = svgToDataUrl(arrowDownRaw);
export const iconArrowUp = svgToDataUrl(arrowUpRaw);
export const iconExport = svgToDataUrl(exportRaw);
export const iconGlossary = svgToDataUrl(glossaryRaw);
export const iconNewProject = svgToDataUrl(newProjectRaw);
export const iconOpenProject = svgToDataUrl(openProjectRaw);
export const iconPause = svgToDataUrl(pauseRaw);
export const iconPlay = svgToDataUrl(playRaw);
export const iconSave = svgToDataUrl(saveRaw);
export const iconSearch = svgToDataUrl(searchRaw);
export const iconSend = svgToDataUrl(sendRaw);
export const iconStop = svgToDataUrl(stopRaw);
export const iconVolume = svgToDataUrl(volumeRaw);
export const iconVolumeMute = svgToDataUrl(volumeMuteRaw);
export const iconWizard = svgToDataUrl(wizardRaw);
export const iconZoomIn = svgToDataUrl(zoomInRaw);
export const iconZoomOut = svgToDataUrl(zoomOutRaw);
